[openai]
api_key = "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"


[tavily]
api_key = "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"
